name = "budakbaong-siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [

  { pattern = "pop.budakbaong.my.id", custom_domain = true },
  { pattern = "ava.game.naver.com.pop.budakbaong.my.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.pop.budakbaong.my.id", custom_domain = true },
  { pattern = "graph.instagram.com.pop.budakbaong.my.id", custom_domain = true },
  { pattern = "help.viu.com.pop.budakbaong.my.id", custom_domain = true },
  { pattern = "support.zoom.us.pop.budakbaong.my.id", custom_domain = true },
  { pattern = "cache.netflix.com.pop.budakbaong.my.id", custom_domain = true },
  { pattern = "graph.facebook.com.pop.budakbaong.my.id", custom_domain = true },
  { pattern = "dogseechew.com.pop.budakbaong.my.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.pop.budakbaong.my.id", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "9825ae32c0ba45c3b906002a26a30f71"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "80b640ff-031d-4294-8b9d-12a41d976444"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/budakbaong02/topnoir1/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/budakbaong02/topnoir1/refs/heads/main/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/budakbaong02/topnoir1/refs/heads/main/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/budakbaong02/topnoir1/refs/heads/main/web/converter.html"
